# 应用名称
spring:
  application:
    name: house
    output:
      ansi:
        enabled: 'always'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123678z
    url: jdbc:mysql://localhost:3306/house?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
# 应用服务 WEB 访问端口

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
  servlet:
    session:
      timeout: 120

